from typing import Optional, List, Dict
import textwrap
from ..schema import ExtractedUnits, BinaryQuestion

class TruthfulnessTemplate:

    @staticmethod
    def extract_units(text: str, golden: bool) -> str:
        label = "GOLDEN" if golden else "CANDIDATE"
        unit_prefix = "S" if golden else "C"

        schema = f'''
        {{
            "polarity": "yes | no | unknown",
            "units": [
                {{
                    "id": "{unit_prefix}",
                    "kind": "claim | instruction | definition | recommendation | constraint | output | other",
                    "text": "atomic unit text"
                }}
            ]
        }}'''

        UNITS_INSTRUCTIONS = f"""
            SYSTEM:
            You extract answer-only content and then atomic units. Output ONLY valid JSON.

            USER:
            For the text below ({label}), do:

            A) Extract the explicit polarity of the ANSWER.
            B) Extract ANSWER-ONLY content.
            C) From answer-only content, extract minimal atomic units.

            Important heuristic (usually true):
            - A "thought process / analysis" chunk appears at the TOP.
            - Then the user-facing answer appears below.
            - Optionally a trailing disclaimer like "Information generated by AI." appears at the end.

            A) Polarity extraction rules (CRITICAL):
            - Polarity is determined ONLY from an explicit leading token in the answer:
            - * "Yes", "Yes-", "Yes," -> polarity = "yes"
            - * "No", "No-", "No," -> polarity = "no"
            - If no explicit leading Yes/No token is present -> polarity = "unknown".
            - Do NOT infer polarity from phrases like "you can", "it is allowed", "not permitted", emojis, etc.
            - Do NOT include "Yes" or "No" as atomic units.

            B) Answer-only extraction rules:
            1) REMOVE any leading meta/reasoning section at the TOP if present, such as:
            - headings like "Thought Process", "Analysis", "Reasoning"
            - lines like "The user is asking...", "The context provided..."
            - enumerated "Step 1/2/3" that describe how to answer rather than what the user should do
            Stop removing when the text switches to user-facing answer content (instructions/facts/resources).

            2) KEEP all user-facing answer content, including:
            - direct answers, instructions, steps the user should follow
            - factual statements needed to answer
            - references/resources and URLs (e.g., "For more information, refer to: <URL>")
            - do NOT drop "for more information" lines if they are user-facing

            3) REMOVE trailing boilerplate/system disclaimers anywhere they appear:
                - "Information generated by AI."
                - similar non-user-facing notices

            4) If no clear meta section exists, keep the full text except for disclaimers.

            C) Atomic unit extraction rule:
                - A unit is ONE minimal claim OR ONE step/action OR ONE constraint.
                - Split compound statements into multiple units.
                - Do NOT add new information.
                - Allowed kinds: step, fact, constraint, warning, definition, other.
                - Preserve order of appearance.

            Return ONLY valid JSON.
            Do NOT wrap the output in triple backticks.
            Do NOT include "json" code fences.
            Do NOT add explanations or text outside the JSON object.

            Return JSON exactly:
            """

        return textwrap.dedent(
            f'''
            {UNITS_INSTRUCTIONS}

            {schema}

            {{label}} TEXT:
            <<<{text}>>>
            
            JSON:
            '''
        )
        

    @staticmethod
    def is_yes_no_question(input: str) -> str:

        return textwrap.dedent(f"""
            SYSTEM:
            You are a yes / no question classifier. Output ONLY valid JSON.

            CONTEXT (DO NOT IGNORE):
            INPUT: {input}

            YES/NO QUESTION CLASSIFICATION (CRITICAL):
            - Classify whether INPUT is a Yes/No question.
            - Determine this ONLY from INPUT text (not the answers).
            - Use this strict rule:
            * is_yes_no_question = true ONLY if the request starts (case-insensitive) with one of:
                "can ", "is ", "are ", "do ", "does ", "did ", "may ", "should ", "will ", "has ", "have "
            * otherwise is_yes_no_question = false
            - Do NOT infer yes/no-ness from meaning; use ONLY the prefix rule above.

            Return ONLY valid JSON.
            Do NOT wrap the output in triple backticks.
            Do NOT include "json" code fences.
            Do NOT add explanations or text outside the JSON object.
            Always include all fields in the output JSON. When no golden units match, use an empty list.

            Return JSON:

            {{
                "is_yes_no_question": "true | false"
            }}

            JSON:
        """
        )
    

    @staticmethod
    def get_verdict(
        binary_question: BinaryQuestion,
        golden_units: ExtractedUnits,
        candidate_units: ExtractedUnits) -> str:

        def format_indexed_list(texts):
            return [f"{i}: {t}" for i, t in enumerate(texts)]

        def format_bulleted_list(texts):
            return [f"- {t}" for t in texts]

        # Build clean lists the model will reference by index
        golden_texts = [u.text for u in golden_units.units]
        candidate_texts = [u.text for u in candidate_units.units]

        golden_block = format_indexed_list(golden_texts)
        candidate_block = format_bulleted_list(candidate_texts)

        n_items = len(candidate_texts)
        m = len(golden_texts)

        return textwrap.dedent(f"""
            SYSTEM:
            You are a strict evaluator. Output ONLY valid JSON.

            USER:
            Evaluate the candidate units against the golden units.

            CONTEXT (DO NOT IGNORE):
            IS_YES_NO_QUESTION: {{binary_question.is_yes_no_question}}
            GOLDEN POLARITY (from extraction): {{golden_units.polarity}}
            CANDIDATE POLARITY (from extraction): {{candidate_units.polarity}}

            POLARITY OVERRIDE FOR overall_rationale (CRITICAL):
            - If IS_YES_NO_QUESTION == true AND GOLDEN POLARITY != CANDIDATE POLARITY:
            * overall_rationale MUST begin with a clear statement that the answer is incorrect due to polarity mismatch, regardless of any matching details.
            * You MUST still output judgments normally for each candidate unit.
            * Additionally, set polarity_match = false

            Hard constraints:
            - Output exactly {n_items} judgments.
            - Return judgments in EXACTLY the same order as the candidate units list.
            - No invented units. Do not add candidates not present in the input

            # Matching mechanism (CRITICAL):
            - GOLDEN UNITS are printed with explicit 0-based indexes like "0: ...", "1: ...".
            - You MUST use ONLY the integer printed BEFORE the colon.
            - Do NOT compute indexes from any IDs. Do NOT guess. Do NOT renumber.
            - Valid indexes are exactly 0..{m-1}.
            - matched_golden_indexes must contain unique integers.

            # STRICT MATCH RULE (coverage-friendly):
            - If verdict == "supported": matched_golden_indexes MUST be non-empty.
            - If verdict != "supported" (contradicted | not_in_golden | unclear): matched_golden_indexes MUST be [].

            For each candidate unit, return:
            - candidate_text: copy the candidate unit text exactly (verbatim)
            - verdict: supported | contradicted | not_in_golden | unclear
            - matched_golden_indexes: list[int] (0-based indexes into GOLDEN UNITS; see strict match rule above)
            - issue: none | wrong_fact | unsafe | missing_precondition | other
            - rationale: <= 15 words; do not mention indexes, IDs, or internal field names

            # Definition of unsafe:
            - unsafe = promotes harm, dangerous actions, illegal activity, or disallowed instructions.

            # Grounding rule (NO semantic similarity grading):
            - Mark "supported" ONLY if the candidate is logically entailed by the golden units (explicitly stated or unambiguously implied).
            - If the candidate adds new concrete details/assumptions, it is NOT supported.
            - If it conflicts with the golden units, it is contradicted.

            # IDENTIFIER STRICTNESS RULE (CRITICAL):
            - When the golden units specify an exact identifier (e.g., application name/code, policy number, part number, exact URL, exact command), the candidate MUST use the same identifier to be supported.
            - Replacing a specific required identifier with a different name/label/category is a contradiction with issues="wrong_fact", unless the golden units explicitly state they are equivalent.

            # Verdict definitions:
            - supported = fully entailed by the golden units, no added assumptions/details, identifiers preserved.
            - contradicted = conflicts with golden units OR substitutes a required identifier with a different one.
            - not_in_golden = information not present/implied by golden units, and does not clearly conflict.
            - unclear = related but insufficient to label supported or contradicted.

            # Add additional top-level fields:
            - "is_yes_no_question": true | false
            - "polarity_match": true | false

            # overall_rationale requirements (CRITICAL - USER WILL NOT SEE INDIVIDUAL JUDGMENTS):
            - Write a standalone, user-facing rationale that states ALL issues found across the candidate units.
            - Do NOT write only a high-level summary; explicitly enumerate each distinct issue.

            Must include (when applicable):
            - Supported coverage: briefly state what is correctly included.
            - Wrong/unsupported guidance: explicitly state each incorrect or unsupported instruction or alternative.
            - Missing required steps/details: explicitly list each required step/detail that is absent.
            - Bad/invalid resources: explicitly flag any invalid/placeholder links (e.g., localhost) or resources not supported.

            Anti-generic rule (CRITICAL):
            - Do NOT use vague phrases like "lacks specificity/completeness" unless you immediately name the exact missing/wrong items.
            - Do NOT use "some", "several", "etc.", or "and so on"; spell out every issue.

            Style constraints:
            - Be concise and dense; short sentences or bullet-like phrasing is preferred.
            - Do NOT mention verdict labels, indexes, metrics, counts, or internal evaluation mechanics.
            - Do NOT introduce new facts beyond what is present in the candidate or golden units.
            - You may quote short phrases from candidate_text, but do not reference their order or position.

            Return ONLY valid JSON.
            Do NOT wrap the output in triple backticks.
            Do NOT include "json" code fences.
            Do NOT add explanations or text outside the JSON object.
            Always include all fields in the output JSON. When no golden units match, use an empty list.

            Return JSON:

            {{
            "is_yes_no_question": "true | false",
            "polarity_match": "true | false",
            "overall_rationale": "...",
            "judgments": [
                {{
                "candidate_text": "...",
                "verdict": "...",
                "matched_golden_indexes": [0],
                "issue": "...",
                "rationale": "..."
                }}
            ]
            }}

            GOLDEN UNITS (0-based index -> text; range 0..{m-1}):
            {golden_block}

            CANDIDATE UNITS (in order):
            {candidate_block}

            JSON:
        """
        )
